build_from:
#  armhf: ghcr.io/home-assistant/armhf-base:3.13
#  armv7: ghcr.io/home-assistant/armv7-base:3.13
  aarch64: redacid/ha-mpd-aarch64:0.0.1
  amd64: redacid/ha-mpd-amd64:0.0.1
#  i386: ghcr.io/home-assistant/i386-base:3.13
